version: '3'

services:
  web:
    container_name: web_django
    build: .
    environment:
      - SECRET_KEY="123"
    command: python WebLearning/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"