# Generated by Django 2.2.2 on 2019-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='tutor',
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
    ]
