# Generated by Django 2.2.2 on 2019-06-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20190604_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='data',
            field=models.DateTimeField(default='2019-06-04 20:00'),
            preserve_default=False,
        ),
    ]
