# Generated by Django 2.2.2 on 2019-06-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20190624_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
    ]
