# Generated by Django 2.2.2 on 2019-06-06 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0004_auto_20190605_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pupils',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
