# Generated by Django 2.2.2 on 2019-06-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_auto_20190624_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
    ]
