# Generated by Django 2.2.2 on 2019-06-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_auto_20190629_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
    ]
