# Generated by Django 2.2.2 on 2019-06-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_course_pupils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pupils',
        ),
    ]
