# Generated by Django 2.2.2 on 2019-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0007_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses_app.Course'),
        ),
    ]
